#!/bin/bash

# change brightness using xbacklight

case "$1" in
    [0-9]*) xbacklight -set "$1" ;;
    +) xbacklight -inc 5 ;;
    -) xbacklight -dec 5 ;;
    *) exit 1 ;;
esac

PERCENT="$(xbacklight -get | cut -d'.' -f1)"

notify-send -u normal -t 1000 -a brightness "luminosité: ${PERCENT}%"

exit 0

# change brightness using sysfs

BRIGHTNESS_PATH="/sys/class/backlight/intel_backlight"
BRIGHTNESS_MAX="max_brightness"
BRIGHTNESS_VAL="brightness"

MAX=$(cat "$BRIGHTNESS_PATH/$BRIGHTNESS_MAX")
VAL=$(cat "$BRIGHTNESS_PATH/$BRIGHTNESS_VAL")

OLD=$(( VAL * 100 / MAX ))

case "$1" in
    [0-9]*) NEW=$1 ;;
    +) NEW=$(( OLD + 5 )) ;;
    -) NEW=$(( OLD - 5 )) ;;
    *) exit 1 ;;
esac

NEW=$(( NEW <= 100 ? NEW : 100 ))
NEW=$(( NEW >= 0 ? NEW : 0 ))

VAL=$(( MAX * NEW / 100 ))

echo $VAL > "$BRIGHTNESS_PATH/$BRIGHTNESS_VAL"

notify-send -u normal -t 1000 -a brightness "luminosité: ${NEW}%"
